import '../../api/sessions/server/publications.js';
import '../../api/jobs/server/publications.js';
import '../../api/userdata/server/publications.js';
import '../../api/timeslots/server/publications.js';
import '../../api/generatedweeks/server/publications.js';
import '../../api/vendordata/server/publications.js';
import '../../api/vendorslots/server/publications.js';
import '../../api/bookings/server/publications.js';
import './timedjobs.js'
